### ISSUE TITLE
Develop MVP Field Service

### ISSUE THREAD

**Issue by Canis1219** [citec-spbu/agro-fields-service#61]
1. Сделать миграции для новой схемы бд. Старую схему можно удалить, либо сделать временно рядом, но тогда временно сделать имена таблиц, которые не дублируются.
2. Описать java jpa сущность для таблицы сезонов. Сделать для неё репозиторий, сервис и контроллер с простыми CRUD операциями(CRUD можете загуглить). Исключая delete операции.
3. Повторить аналогично пункту 2 с остальными таблицами, делая всё итеративно. Очевидно, что fields и contours надо будет делать в один заход две таблицы, так как при создании поля, мы его создаём уже с контурами сразу, как и удаляем. То есть эта история неделимая, такой её и оставим

P.S. URL'ы называйте похожим образом, как уже есть на проект, только вместо v1 пишите v2. Для сервисов важно соблюсти следующее, они получают сущности и отдают сущности. На уровне сервисов не работать с DTO классами из контроллеров. Контроллеры могут возвращать jpa сущности и их коллекции, это ок. Для маппинга dto в сущности и наоборот используем: ModelMapper, ObjectMapper или mapstruct, если маппинг сложный. Только в крайнем случае пишем маппинг руками.

Ахтунг: заведите пакет v2 в пакете agroscience.team и в нём пока делайте вторую версию. Как всё будет готово, вырежем первую версию и перенесём пакеты в v2 на уровень выше

**Comment by asavershin** [comment]
Продублирую комментом

Не делайте удаление в рамках этой задачи. Удалять объекты сложнее всего, для этого заведены отдельные задачи #67 и #66
